import { test, expect } from '@playwright/test'

test('生成、检索、收藏、持久化与导出报告', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: '开始调研' })).toBeDisabled()
  await page.getByLabel('调研问题', { exact: true }).fill('企业知识库的技术选型')
  await page.getByRole('button', { name: '开始调研' }).click()
  await expect(page.getByText('正在构建演示报告')).toBeVisible()
  await expect(page.getByRole('heading', { name: '企业知识库的技术选型', exact: true })).toBeVisible({ timeout: 10000 })
  await page.getByRole('button', { name: '收藏：摘要与核心问题', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '取消收藏：摘要与核心问题', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('报告内全文搜索').fill('不存在的关键词abcdef')
  await expect(page.getByRole('heading', { name: '未找到相关内容' })).toBeVisible()
  await page.getByLabel('报告内全文搜索').fill('评分')
  await expect(page.locator('.report-chapter')).toHaveCount(1)
  await expect(page.locator('mark').first()).toHaveText('评分')
  await page.getByRole('button', { name: '数据', exact: true }).click()
  await expect(page.getByRole('table')).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByLabel('导出格式').selectOption('html')
  await page.getByRole('button', { name: '导出', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('企业知识库的技术选型.html')
  await page.getByRole('link', { name: '返回报告', exact: true }).click()
  await page.getByRole('link', { name: /企业知识库的技术选型/ }).click()
  await expect(page.getByRole('heading', { name: '企业知识库的技术选型', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('取消生成不会创建报告，报告库支持全文检索', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('调研问题', { exact: true }).fill('需要取消的任务')
  await page.getByRole('button', { name: '开始调研' }).click()
  await page.getByRole('button', { name: '取消生成' }).click()
  await expect(page.getByRole('button', { name: '开始调研' })).toBeEnabled()
  await page.getByRole('link', { name: '全部报告' }).click()
  await expect(page.locator('.report-card')).toHaveCount(3)
  await page.getByLabel('搜索报告或书签').fill('RAG')
  await expect(page.locator('.report-card')).toHaveCount(1)
  await page.getByLabel('搜索报告或书签').fill('可追溯')
  await expect(page.locator('.report-card')).toHaveCount(3)
  await page.goto('/#/report/missing')
  await expect(page.getByRole('heading', { name: '这份报告不在当前工作空间' })).toBeVisible()
})
